Create reset password API endpoint
GTBitsOfGood/hope-sustains-life pull request #167
Opened 2022-02-03 01:32 UTC by its-edmund

## PR Title/Tagline

Issue Number(s): #number_of_issue. 

What does this PR change and why?

### Checklist

- [ ]  Database schema docs have been updated or are not necessary
- [ ]  Code follows design and style guidelines
- [ ]  Code is commented with doc blocks
- [ ]  Tests have been written and executed or are not necessary
- [ ]  Latest code has been rebased from base branch (usually `develop`)
- [ ]  Commits follow guidelines (concise, squashed, etc)
- [ ]  Github issues have been linked in relevant commits
- [ ]  Relevant reviewers (Senior Dev/EM/Designers) have been assigned to this PR

### Critical Changes

- Database change / migration to run
- Environment config change
- Breaking API change

### Related PRs

- #PRNUMBER

### How to Test

1. Please add or build upon a testing card to the [Notion page](http://notion.so) and link it here

2022-02-03 01:33 UTC, its-edmund commented
Still needs #162 to be finished before this PR is done.

2022-02-12 01:35 UTC, kphan32 requested changes

2022-02-12 01:35 UTC, kphan32 commented on server/mongodb/actions/ResetUser.js
> +  if (password == null) {
The token should be validated as well

2022-02-12 01:35 UTC, kphan32 commented on src/pages/api/users/resetpassword.js
> +  }
Should send a response for other methods as well.

2022-02-12 01:36 UTC, kphan32 commented on server/mongodb/actions/ResetUser.js
> +  const request = await PasswordResetRequest.find({ token: token });
Nit: use `findOne`

2022-02-17 15:09 UTC, kphan32 requested changes
Very close! Reminder to test changes before submitting for review.

2022-02-17 15:21 UTC, kphan32 commented
Also thought of this while looking at Luke's PR-- I think the actual endpoint to access this API should be `api/users?action=RESETPASSWORD` to maintain consistency. This is on me for not catching this earlier on, so feel free to resolve the previous changes and ping me so I can do this part.

2022-02-24 01:55 UTC, kphan32 commented on server/mongodb/actions/ResetUser.js
> +  );
nice

2022-02-24 02:00 UTC, kphan32 approved these changes
lgtm :+1:

2022-02-24 02:02 UTC, merged